POST http://localhost:3000/api/
Content-Type:  application/json

{
    "postId": "b64865fa-978e-45aa-814a-4a77866a90bf",
    "username": "test",
    "email": "admin@admin.fr",
    "content": "efoisehgiuqrhg"
}

###
DELETE http://localhost:3000/api/users/
Content-Type: application/json

{
"id":"1"
}

