GET http://localhost:3000/api/comments
Content-Type:  application/json

{
    "postId": "b64865fa-978e-45aa-814a-4a77866a90bf",
    "username": "test",
    "email": "admin@admin.fr",
    "content": "efoisehgiuqrhg"
}

###
DELETE http://localhost:3000/api/comments/322e310c-0e1e-483e-b86e-f266d53c5c38
Content-Type: application/json

{
    
}

