POST http://localhost:3000/api/auth/register
Content-Type:  application/json

{
   
    "name": "Mathieu Bazard",
    "email": "southwestfishing@gmail.com",
    "password":"admin1337"
}

###
DELETE http://localhost:3000/api/comments/322e310c-0e1e-483e-b86e-f266d53c5c38
Content-Type: application/json

{
    
}

###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "username": "test",
    "email": "azdzd"
}